name: Continuous Integration & Deployment

on:
  push:
    branches:
      - main

jobs:
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: |
          git fetch --prune --unshallow
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.11
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.11

  run_tests:
    name: Run all tests for solution
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install dependencies and build tools
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: '6.0.x'

      - name: Run tests
        run: dotnet test

  publish_nuget:
    name: Publish new NuGet package version
    runs-on: ubuntu-latest
    needs:
      - calculate-version
      - run_tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install dependencies and build tools
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: '6.0.x'

      - name: Publish package
        uses: rohith/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: src/Embargoed.AspNetCore/Embargoed.AspNetCore.csproj
          PACKAGE_NAME: Embargoed.AspNetCore
          VERSION_STATIC: ${{ needs.calculate-version.outputs.semVer }}
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
