name: Continuous Integration

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
 run_tests:
    name: Run all tests for solution
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install dependencies and build tools
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: '6.0.x'

      - name: Run tests
        run: dotnet test
